version: "3"
networks: 
 expense:
volumes:
 mysql:
services:
 mysql:
  image: mysql:v1
  container_name: mysql
  volumes: 
   - mysql:/var/lib/mysql
 backend:
  image:  backend:v1
  container_name: backend
  depends_on: 
   - mysql
 frontend:
   image:  backend:v1
   container_name: frontend
   depends_on: 
    - backend
   
