version: "3.8"

networks:
  expense:

volumes:
  mysql:

services:
  mysql:
    image: mysql:5.7  # Updated to a specific version for clarity
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - expense
    environment:
      MYSQL_ROOT_PASSWORD: example  # Set root password for MySQL

  backend:
    image: backend:v1
    container_name: backend
    depends_on:
      - mysql
    networks:
      - expense

  frontend:
    image: frontend:v1  # Assuming a different image for the frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - expense
